### ISSUE TITLE
Themes and Dark/Light Toggling

### ISSUE THREAD

**Issue by pacocoursey** [hundredrabbits/Themes#12]
Left recently introduced a theme toggle button. This would replace the theme with either Noir or Pale as light and dark versions.

I'm a big fan of offering a theme toggle, but this solution overrides any previous applied theme. For example: if you had Lotus active and clicked the theme toggle, it would override Lotus with Pale with no way to return to Lotus without re-dragging the theme file.

A few solutions come to mind:
- Change nothing.
- Update themes so that they can specify an alternate version and switch between them. i.e.
```js
// lotus.thm

{
  "meta": {},
  "data-light": {
    // ...
  },
  "data-dark": {
    // ...
  }
}
```
- Apply a `filter: invert(100%)` class, which automatically inverts the specified theme colors. It actually looks pretty good, but could also cause problems. Here are some examples:

<img width="2664" alt="ccc" src="https://user-images.githubusercontent.com/34928425/44420777-15f81200-a53c-11e8-8b7d-857290d753f4.png">

Just trying to promote some discussion around this to make it easy to implement theme toggles in the ecosystem applications. Let me know your thoughts.

**Comment by kormyen** [comment]
I like the idea of themes specifying their own 'light' and 'dark' colors.

I wonder if 'toggling' light mode/dark mode would work as swapping the theme's f/b colors? (the themes do not currently work like that atm but wondering if that would work as a convention rather than requiring an additional set of colors).

I'm against using 'filter invert' as I don't think light mode/dark mode are necessarily just exact opposites, especially in terms of an ascent color for the app / style guide.
